DROP TABLE "JJIM";
DROP TABLE "MESSAGE";
DROP TABLE "SHARE_COMMENT";
DROP TABLE "COMMENT";
DROP TABLE "BOARD_IMAGE";
DROP TABLE "SHARE";
DROP TABLE "BOARD";
DROP TABLE "SHARE_CATEGORY_DETAIL";
DROP TABLE "SHARE_CATEGORY";
DROP TABLE "BOARD_TYPE";
DROP TABLE "AUTHKEY";
DROP TABLE "MEMBER";

DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_KEY_NUM;
DROP SEQUENCE SEQ_BOARD_CODE;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_IMG_NO;
DROP SEQUENCE SEQ_SHARE_BOARD_CATEGORY_CODE;
DROP SEQUENCE SEQ_SHARE_BOARD_CATEGORY_DETAIL_CODE;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_MESSAGE_NO;

CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
CREATE TABLE "MEMBER" (
    "MEMBER_NO" NUMBER PRIMARY KEY,
    "MEMBER_ID" NVARCHAR2(15) NOT NULL,
    "MEMBER_PW" NVARCHAR2(100) NOT NULL,
    "MEMBER_NICKNAME" NVARCHAR2(10) NOT NULL,
    "MEMBER_EMAIL" NVARCHAR2(50) NOT NULL,
    "MEMBER_TEL" CHAR(11) NOT NULL,
    "MEMBER_ADDRESS" NVARCHAR2(300),
    "ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "MEMBER_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("MEMBER_DEL_FL" IN ('Y', 'N')),
    "AUTHORITY" NUMBER DEFAULT 1 NOT NULL CHECK ("AUTHORITY" IN (0,1)),
    "MEMBER_IMG" NVARCHAR2(300)
);
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입 날짜';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 삭제 여부';
COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '관리자 : 0 / 일반 사용자 : 1';
COMMENT ON COLUMN "MEMBER"."MEMBER_IMG" IS '회원이미지';

ALTER TABLE MEMBER MODIFY MEMBER_PW NVARCHAR2(100);

CREATE SEQUENCE SEQ_KEY_NUM NOCACHE NOCYCLE;
CREATE TABLE "AUTHKEY" (
    "KEY_NUM" NUMBER NOT NULL,
    "AUTH_EMAIL" NVARCHAR2(50) NOT NULL,
    "AUTH_KEY" NVARCHAR2(6) NOT NULL,
    "CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL
);
COMMENT ON COLUMN "AUTHKEY"."KEY_NUM" IS '인증키 시퀀스';
COMMENT ON COLUMN "AUTHKEY"."AUTH_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "AUTHKEY"."AUTH_KEY" IS '인증 번호';
COMMENT ON COLUMN "AUTHKEY"."CREATE_TIME" IS '인증 번호 생성 시간';


-- 테스트를 위한 샘플 데이터 삽입
INSERT INTO "AUTHKEY" VALUES (SEQ_KEY_NUM.NEXTVAL, 'test@example.com', '123456', SYSDATE);

-- 작업 확인
SELECT * FROM USER_SCHEDULER_JOBS WHERE JOB_NAME LIKE 'DELETE_AUTHKEY_%';

-- 삭제 확이
SELECT * FROM "AUTHKEY" WHERE "AUTH_EMAIL" = 'test@example.com';
SELECT * FROM AUTHKEY;





CREATE TABLE "BOARD_TYPE" (
    "BOARD_CODE" NUMBER PRIMARY KEY,
    "BOARD_NAME" NVARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판종류코드번호(PK)';
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판이름';


CREATE SEQUENCE SEQ_BOARD_CODE NOCACHE NOCYCLE;
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '나눔게시판');
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '자유게시판');
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '공지게시판');
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '문의게시판');
SELECT * FROM BOARD_TYPE;



CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

CREATE TABLE "BOARD" (
    "BOARD_NO" NUMBER PRIMARY KEY,
    "BOARD_TITLE" NVARCHAR2(100) NOT NULL,
    "BOARD_CONTENT" NVARCHAR2(2000) NOT NULL,
    "BOARD_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "BOARD_UPDATE_DATE" DATE,
    "READ_COUNT" NUMBER DEFAULT 0 NOT NULL,
    "BOARD_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("BOARD_DEL_FL" IN ('Y', 'N')),
    "BOARD_CODE" NUMBER NOT NULL,
    "MEMBER_NO" NUMBER NOT NULL,
    "QA_STATUS" CHAR(1) DEFAULT 'N' CHECK ("QA_STATUS" IN ('Y', 'N')),
    FOREIGN KEY ("BOARD_CODE") REFERENCES "BOARD_TYPE" ("BOARD_CODE"),
    FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);
COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(PK)';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';
COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';
COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';
COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '게시글 조회수';
COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부 (Y/N)';
COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 코드번호(FK)';
COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "BOARD"."QA_STATUS" IS '문의게시글 답변 상태 (Y/N)';



CREATE SEQUENCE SEQ_IMG_NO NOCACHE NOCYCLE;

CREATE TABLE "BOARD_IMAGE" (
    "IMG_NO" NUMBER PRIMARY KEY,
    "IMG_PATH" NVARCHAR2(200) NOT NULL,
    "IMG_ORIGINAL_NAME" NVARCHAR2(50) NOT NULL,
    "IMG_RENAME" NVARCHAR2(50) NOT NULL,
    "IMG_ORDER" NUMBER NOT NULL,
    "BOARD_NO" NUMBER NOT NULL,
    FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO")
);
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_NO" IS '이미지 번호(PK)';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_PATH" IS '이미지주소';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_ORIGINAL_NAME" IS '이미지원본명';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_RENAME" IS '이미지원본명';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_ORDER" IS '이미지순서';
COMMENT ON COLUMN "BOARD_IMAGE"."BOARD_NO" IS '게시글 번호(FK)';



CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE NOCYCLE;

CREATE TABLE "COMMENT" (
    "COMMENT_NO" NUMBER PRIMARY KEY,
    "COMMENT_CONTENT" NVARCHAR2(2000) NOT NULL,
    "COMMENT_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "COMMENT_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("COMMENT_DEL_FL" IN ('Y', 'N')),
    "BOARD_NO" NUMBER NOT NULL,
    "PARENT_COMMENT_NO" NUMBER,
    "MEMBER_NO" NUMBER NOT NULL,
    FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO"),
    FOREIGN KEY ("PARENT_COMMENT_NO") REFERENCES "COMMENT" ("COMMENT_NO"),
    FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);
COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호(PK)';
COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글내용';
COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '작성일';
COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글삭제 여부(Y/N)';
COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호(FK)';
COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모댓글번호(FK)';
COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 고유번호(PK)';



CREATE TABLE "SHARE_CATEGORY" (
    "SHARE_BOARD_CATEGORY_CODE" NUMBER DEFAULT 0 CHECK ("SHARE_BOARD_CATEGORY_CODE" IN (0,1)) PRIMARY KEY,
    "SHARE_BOARD_CATEGORY_NAME" NVARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN "SHARE_CATEGORY"."SHARE_BOARD_CATEGORY_CODE" IS '물품 : 0 / 재능 1';
COMMENT ON COLUMN "SHARE_CATEGORY"."SHARE_BOARD_CATEGORY_NAME" IS '세부 카테고리 이름';

CREATE TABLE "SHARE_CATEGORY_DETAIL" (
    "SHARE_BOARD_CATEGORY_DETAIL_CODE" NUMBER DEFAULT 0 PRIMARY KEY,
    "SHARE_BOARD_CATEGORY_DETAIL_NAME" NVARCHAR2(20) NOT NULL,
    "SHARE_BOARD_CATEGORY_CODE" NUMBER DEFAULT 0 NOT NULL,
    FOREIGN KEY ("SHARE_BOARD_CATEGORY_CODE") REFERENCES "SHARE_CATEGORY" ("SHARE_BOARD_CATEGORY_CODE")
);
COMMENT ON COLUMN "SHARE_CATEGORY_DETAIL"."SHARE_BOARD_CATEGORY_DETAIL_CODE" IS '여러 기부 종류에 대한 코드';
COMMENT ON COLUMN "SHARE_CATEGORY_DETAIL"."SHARE_BOARD_CATEGORY_DETAIL_NAME" IS '세부 카테고리 이름';
COMMENT ON COLUMN "SHARE_CATEGORY_DETAIL"."SHARE_BOARD_CATEGORY_CODE" IS '물품 : 0 / 재능 1';


CREATE SEQUENCE SEQ_SHARE_BOARD_CATEGORY_CODE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SHARE_BOARD_CATEGORY_DETAIL_CODE NOCACHE NOCYCLE;

INSERT INTO SHARE_CATEGORY VALUES (0, '물건');
INSERT INTO SHARE_CATEGORY VALUES (1, '재능');

-- 물건 나눔 (SHARE_BOARD_CATEGORY_CODE = 0)
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (0, '디지털 기기', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (1, '생활 가전', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (2, '의류/잡화', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (3, '스포츠', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (4, '취미/게임/음반', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (5, '도서', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (6, '기타', 0);

-- 재능 나눔 (SHARE_BOARD_CATEGORY_CODE = 1)
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (10, '교육 및 멘토링', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (11, '예술 및 문화', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (12, '디자인 및 콘텐츠', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (13, 'IT 및 기술', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (14, '법률·세무·경영 자문', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (15, '의료 및 건강', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (16, '생활 서비스', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (17, '번역 및 통역', 1);

SELECT * FROM SHARE_CATEGORY;
SELECT * FROM SHARE_CATEGORY_DETAIL;



CREATE TABLE "SHARE" (
    "BOARD_NO" NUMBER PRIMARY KEY,
    "BOARD_TITLE" NVARCHAR2(100) NOT NULL,
    "BOARD_CONTENT" NVARCHAR2(2000) NOT NULL,
    "BOARD_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "BOARD_UPDATE_DATE" DATE,
    "READ_COUNT" NUMBER DEFAULT 0 NOT NULL,
    "BOARD_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("BOARD_DEL_FL" IN ('Y', 'N')),
    "MEMBER_NO" NUMBER NOT NULL,
    "BOARD_CODE" NUMBER NOT NULL,
    "SHARE_STATUS" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("SHARE_STATUS" IN ('Y', 'N')),
    "SHARE_BOARD_CATEGORY_DETAIL_CODE" NUMBER DEFAULT 0 NOT NULL,
    FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
    FOREIGN KEY ("BOARD_CODE") REFERENCES "BOARD_TYPE" ("BOARD_CODE"),
    FOREIGN KEY ("SHARE_BOARD_CATEGORY_DETAIL_CODE") REFERENCES "SHARE_CATEGORY_DETAIL" ("SHARE_BOARD_CATEGORY_DETAIL_CODE")
);
COMMENT ON COLUMN "SHARE"."BOARD_NO" IS '나눔 게시글 번호(PK)';
COMMENT ON COLUMN "SHARE"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "SHARE"."BOARD_CONTENT" IS '게시글 내용';
COMMENT ON COLUMN "SHARE"."BOARD_WRITE_DATE" IS '게시글 작성일';
COMMENT ON COLUMN "SHARE"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';
COMMENT ON COLUMN "SHARE"."READ_COUNT" IS '게시글 조회수';
COMMENT ON COLUMN "SHARE"."BOARD_DEL_FL" IS '게시글 삭제 여부 (Y/N)';
COMMENT ON COLUMN "SHARE"."MEMBER_NO" IS '회원 고유번호(FK)';
COMMENT ON COLUMN "SHARE"."BOARD_CODE" IS '게시판종류코드번호(PK)';
COMMENT ON COLUMN "SHARE"."SHARE_STATUS" IS '나눔상태(Y/N)';
COMMENT ON COLUMN "SHARE"."SHARE_BOARD_CATEGORY_DETAIL_CODE" IS '물품 : 0 -7 / 재능 0-8';



CREATE TABLE "SHARE_COMMENT" (
    "COMMENT_NO" NUMBER PRIMARY KEY,
    "COMMENT_CONTENT" NVARCHAR2(2000) NOT NULL,
    "COMMENT_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "COMMENT_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("COMMENT_DEL_FL" IN ('Y', 'N')),
    "MEMBER_NO" NUMBER NOT NULL,
    "BOARD_NO" NUMBER NOT NULL,
    "PARENT_COMMENT_NO" NUMBER,
    FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
    FOREIGN KEY ("BOARD_NO") REFERENCES "SHARE" ("BOARD_NO"),
    FOREIGN KEY ("PARENT_COMMENT_NO") REFERENCES "SHARE_COMMENT" ("COMMENT_NO")
);
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_NO" IS '댓글번호(PK)';
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_CONTENT" IS '댓글내용';
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_WRITE_DATE" IS '작성일';
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_DEL_FL" IS '댓글삭제 여부(Y/N)';
COMMENT ON COLUMN "SHARE_COMMENT"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "SHARE_COMMENT"."BOARD_NO" IS '나눔 게시글 번호(PK)';
COMMENT ON COLUMN "SHARE_COMMENT"."PARENT_COMMENT_NO" IS '부모댓글번호(FK)';



CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE NOCYCLE;

CREATE TABLE "MESSAGE" (
    "MESSAGE_NO" NUMBER PRIMARY KEY,
    "MESSAGE_TEXT" NVARCHAR2(2000) NOT NULL,
    "MESSAGE_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "MESSAGE_READ_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("MESSAGE_READ_FL" IN ('Y', 'N')),
    "MESSAGE_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("MESSAGE_DEL_FL" IN ('Y', 'N')),
    "BOARD_NO" NUMBER NOT NULL,
    "SENDER_NO" NUMBER NOT NULL,
    "RECEIVER_NO" NUMBER NOT NULL,
    FOREIGN KEY ("BOARD_NO") REFERENCES "SHARE" ("BOARD_NO"),
    FOREIGN KEY ("SENDER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
    FOREIGN KEY ("RECEIVER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);
COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '쪽지번호(PK)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_TEXT" IS '쪽지내용';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_WRITE_DATE" IS '쪽지를 작성한 날짜';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_READ_FL" IS '쪽지 읽기 여부(Y/N)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_DEL_FL" IS '쪽지 삭제 여부(Y/N)';
COMMENT ON COLUMN "MESSAGE"."BOARD_NO" IS '나눔 게시글 번호(FK)';
COMMENT ON COLUMN "MESSAGE"."SENDER_NO" IS '회원 고유번호( FK)';
COMMENT ON COLUMN "MESSAGE"."RECEIVER_NO" IS '회원 고유번호(FK)';



CREATE TABLE "JJIM" (
    "MEMBER_NO" NUMBER NOT NULL,
    "BOARD_NO" NUMBER NOT NULL,
    PRIMARY KEY ("MEMBER_NO", "BOARD_NO"),
    FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
    FOREIGN KEY ("BOARD_NO") REFERENCES "SHARE" ("BOARD_NO")
);
COMMENT ON COLUMN "JJIM"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "JJIM"."BOARD_NO" IS '나눔 게시글 번호(PFK)';
