DROP TABLE "JJIM";
DROP TABLE "MESSAGE";
DROP TABLE "SHARE_COMMENT";
DROP TABLE "COMMENT";
DROP TABLE "BOARD_IMAGE";
DROP TABLE "SHARE";
DROP TABLE "BOARD";
DROP TABLE "SHARE_CATEGORY_DETAIL";
DROP TABLE "SHARE_CATEGORY";
DROP TABLE "BOARD_TYPE";
DROP TABLE "AUTHKEY";
DROP TABLE "MEMBER";
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_KEY_NUM;
DROP SEQUENCE SEQ_BOARD_CODE;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_IMG_NO;
DROP SEQUENCE SEQ_SHARE_BOARD_CATEGORY_CODE;
DROP SEQUENCE SEQ_SHARE_BOARD_CATEGORY_DETAIL_CODE;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_MESSAGE_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
CREATE TABLE "MEMBER" (
   "MEMBER_NO" NUMBER PRIMARY KEY,
   "MEMBER_ID" NVARCHAR2(15) NOT NULL,
   "MEMBER_PW" NVARCHAR2(20) NOT NULL,
   "MEMBER_NICKNAME" NVARCHAR2(10) NOT NULL,
   "MEMBER_EMAIL" NVARCHAR2(50) NOT NULL,
   "MEMBER_TEL" CHAR(11) NOT NULL,
   "MEMBER_ADDRESS" NVARCHAR2(300),
   "ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
   "MEMBER_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("MEMBER_DEL_FL" IN ('Y', 'N')),
   "AUTHORITY" NUMBER DEFAULT 1 NOT NULL CHECK ("AUTHORITY" IN (0,1)),
   "MEMBER_IMG" NVARCHAR2(300)
);

SELECT * FROM "MEMBER";

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입 날짜';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 삭제 여부';
COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '관리자 : 0 / 일반 사용자 : 1';
COMMENT ON COLUMN "MEMBER"."MEMBER_IMG" IS '회원이미지';
CREATE SEQUENCE SEQ_KEY_NUM NOCACHE NOCYCLE;
CREATE TABLE "AUTHKEY" (
   "KEY_NUM" NUMBER NOT NULL,
   "AUTH_EMAIL" NVARCHAR2(50) NOT NULL,
   "AUTH_KEY" NVARCHAR2(6) NOT NULL,
   "CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL
);
COMMENT ON COLUMN "AUTHKEY"."KEY_NUM" IS '인증키 시퀀스';
COMMENT ON COLUMN "AUTHKEY"."AUTH_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "AUTHKEY"."AUTH_KEY" IS '인증 번호';
COMMENT ON COLUMN "AUTHKEY"."CREATE_TIME" IS '인증 번호 생성 시간';
-- 테스트를 위한 샘플 데이터 삽입
INSERT INTO "AUTHKEY" VALUES (SEQ_KEY_NUM.NEXTVAL, 'test@example.com', '123456', SYSDATE);
-- 작업 확인
SELECT * FROM USER_SCHEDULER_JOBS WHERE JOB_NAME LIKE 'DELETE_AUTHKEY_%';
-- 삭제 확인
SELECT * FROM "AUTHKEY" WHERE "AUTH_EMAIL" = 'test@example.com';
SELECT * FROM AUTHKEY;
CREATE TABLE "BOARD_TYPE" (
   "BOARD_CODE" NUMBER PRIMARY KEY,
   "BOARD_NAME" NVARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판종류코드번호(PK)';
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판이름';
CREATE SEQUENCE SEQ_BOARD_CODE NOCACHE NOCYCLE;
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '나눔게시판');
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '자유게시판');
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '공지게시판');
INSERT INTO BOARD_TYPE VALUES (SEQ_BOARD_CODE.NEXTVAL, '문의게시판');
SELECT * FROM BOARD_TYPE;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;
CREATE TABLE "BOARD" (
   "BOARD_NO" NUMBER PRIMARY KEY,
   "BOARD_TITLE" NVARCHAR2(100) NOT NULL,
   "BOARD_CONTENT" NVARCHAR2(2000) NOT NULL,
   "BOARD_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
   "BOARD_UPDATE_DATE" DATE,
   "READ_COUNT" NUMBER DEFAULT 0 NOT NULL,
   "BOARD_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("BOARD_DEL_FL" IN ('Y', 'N')),
   "BOARD_CODE" NUMBER NOT NULL,
   "MEMBER_NO" NUMBER NOT NULL,
   "QA_STATUS" CHAR(1) DEFAULT 'N' CHECK ("QA_STATUS" IN ('Y', 'N')),
   FOREIGN KEY ("BOARD_CODE") REFERENCES "BOARD_TYPE" ("BOARD_CODE"),
   FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);
COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(PK)';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';
COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';
COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';
COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '게시글 조회수';
COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부 (Y/N)';
COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 코드번호(FK)';
COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "BOARD"."QA_STATUS" IS '문의게시글 답변 상태 (Y/N)';
CREATE SEQUENCE SEQ_IMG_NO NOCACHE NOCYCLE;
CREATE TABLE "BOARD_IMAGE" (
   "IMG_NO" NUMBER PRIMARY KEY,
   "IMG_PATH" NVARCHAR2(200) NOT NULL,
   "IMG_ORIGINAL_NAME" NVARCHAR2(50) NOT NULL,
   "IMG_RENAME" NVARCHAR2(50) NOT NULL,
   "IMG_ORDER" NUMBER NOT NULL,
   "BOARD_NO" NUMBER NOT NULL,
   FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO")
);
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_NO" IS '이미지 번호(PK)';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_PATH" IS '이미지주소';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_ORIGINAL_NAME" IS '이미지원본명';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_RENAME" IS '이미지원본명';
COMMENT ON COLUMN "BOARD_IMAGE"."IMG_ORDER" IS '이미지순서';
COMMENT ON COLUMN "BOARD_IMAGE"."BOARD_NO" IS '게시글 번호(FK)';
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE NOCYCLE;
CREATE TABLE "COMMENT" (
   "COMMENT_NO" NUMBER PRIMARY KEY,
   "COMMENT_CONTENT" NVARCHAR2(2000) NOT NULL,
   "COMMENT_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
   "COMMENT_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("COMMENT_DEL_FL" IN ('Y', 'N')),
   "BOARD_NO" NUMBER NOT NULL,
   "PARENT_COMMENT_NO" NUMBER,
   "MEMBER_NO" NUMBER NOT NULL,
   FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO"),
   FOREIGN KEY ("PARENT_COMMENT_NO") REFERENCES "COMMENT" ("COMMENT_NO"),
   FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);
COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호(PK)';
COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글내용';
COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '작성일';
COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글삭제 여부(Y/N)';
COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호(FK)';
COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모댓글번호(FK)';
COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 고유번호(PK)';
CREATE TABLE "SHARE_CATEGORY" (
   "SHARE_BOARD_CATEGORY_CODE" NUMBER DEFAULT 0 CHECK ("SHARE_BOARD_CATEGORY_CODE" IN (0,1)) PRIMARY KEY,
   "SHARE_BOARD_CATEGORY_NAME" NVARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN "SHARE_CATEGORY"."SHARE_BOARD_CATEGORY_CODE" IS '물품 : 0 / 재능 1';
COMMENT ON COLUMN "SHARE_CATEGORY"."SHARE_BOARD_CATEGORY_NAME" IS '세부 카테고리 이름';
CREATE TABLE "SHARE_CATEGORY_DETAIL" (
   "SHARE_BOARD_CATEGORY_DETAIL_CODE" NUMBER DEFAULT 0 PRIMARY KEY,
   "SHARE_BOARD_CATEGORY_DETAIL_NAME" NVARCHAR2(20) NOT NULL,
   "SHARE_BOARD_CATEGORY_CODE" NUMBER DEFAULT 0 NOT NULL,
   FOREIGN KEY ("SHARE_BOARD_CATEGORY_CODE") REFERENCES "SHARE_CATEGORY" ("SHARE_BOARD_CATEGORY_CODE")
);
COMMENT ON COLUMN "SHARE_CATEGORY_DETAIL"."SHARE_BOARD_CATEGORY_DETAIL_CODE" IS '여러 기부 종류에 대한 코드';
COMMENT ON COLUMN "SHARE_CATEGORY_DETAIL"."SHARE_BOARD_CATEGORY_DETAIL_NAME" IS '세부 카테고리 이름';
COMMENT ON COLUMN "SHARE_CATEGORY_DETAIL"."SHARE_BOARD_CATEGORY_CODE" IS '물품 : 0 / 재능 1';
CREATE SEQUENCE SEQ_SHARE_BOARD_CATEGORY_CODE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SHARE_BOARD_CATEGORY_DETAIL_CODE NOCACHE NOCYCLE;
INSERT INTO SHARE_CATEGORY VALUES (0, '물건');
INSERT INTO SHARE_CATEGORY VALUES (1, '재능');
-- 물건 나눔 (SHARE_BOARD_CATEGORY_CODE = 0)
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (0, '디지털 기기', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (1, '생활 가전', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (2, '의류/잡화', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (3, '스포츠', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (4, '취미/게임/음반', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (5, '도서', 0);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (6, '기타', 0);
-- 재능 나눔 (SHARE_BOARD_CATEGORY_CODE = 1)
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (10, '교육 및 멘토링', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (11, '예술 및 문화', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (12, '디자인 및 콘텐츠', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (13, 'IT 및 기술', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (14, '법률·세무·경영 자문', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (15, '의료 및 건강', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (16, '생활 서비스', 1);
INSERT INTO SHARE_CATEGORY_DETAIL VALUES (17, '번역 및 통역', 1);
SELECT * FROM SHARE_CATEGORY;
SELECT * FROM SHARE_CATEGORY_DETAIL;
CREATE TABLE "SHARE" (
   "BOARD_NO" NUMBER PRIMARY KEY,
   "BOARD_TITLE" NVARCHAR2(100) NOT NULL,
   "BOARD_CONTENT" NVARCHAR2(2000) NOT NULL,
   "BOARD_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
   "BOARD_UPDATE_DATE" DATE,
   "READ_COUNT" NUMBER DEFAULT 0 NOT NULL,
   "BOARD_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("BOARD_DEL_FL" IN ('Y', 'N')),
   "MEMBER_NO" NUMBER NOT NULL,
   "BOARD_CODE" NUMBER NOT NULL,
   "SHARE_STATUS" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("SHARE_STATUS" IN ('Y', 'N')),
   "SHARE_BOARD_CATEGORY_DETAIL_CODE" NUMBER DEFAULT 0 NOT NULL,
   FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
   FOREIGN KEY ("BOARD_CODE") REFERENCES "BOARD_TYPE" ("BOARD_CODE"),
   FOREIGN KEY ("SHARE_BOARD_CATEGORY_DETAIL_CODE") REFERENCES "SHARE_CATEGORY_DETAIL" ("SHARE_BOARD_CATEGORY_DETAIL_CODE")
);
COMMENT ON COLUMN "SHARE"."BOARD_NO" IS '나눔 게시글 번호(PK)';
COMMENT ON COLUMN "SHARE"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "SHARE"."BOARD_CONTENT" IS '게시글 내용';
COMMENT ON COLUMN "SHARE"."BOARD_WRITE_DATE" IS '게시글 작성일';
COMMENT ON COLUMN "SHARE"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';
COMMENT ON COLUMN "SHARE"."READ_COUNT" IS '게시글 조회수';
COMMENT ON COLUMN "SHARE"."BOARD_DEL_FL" IS '게시글 삭제 여부 (Y/N)';
COMMENT ON COLUMN "SHARE"."MEMBER_NO" IS '회원 고유번호(FK)';
COMMENT ON COLUMN "SHARE"."BOARD_CODE" IS '게시판종류코드번호(PK)';
COMMENT ON COLUMN "SHARE"."SHARE_STATUS" IS '나눔상태(Y/N)';
COMMENT ON COLUMN "SHARE"."SHARE_BOARD_CATEGORY_DETAIL_CODE" IS '물품 : 0 -7 / 재능 0-8';
CREATE TABLE "SHARE_COMMENT" (
   "COMMENT_NO" NUMBER PRIMARY KEY,
   "COMMENT_CONTENT" NVARCHAR2(2000) NOT NULL,
   "COMMENT_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
   "COMMENT_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("COMMENT_DEL_FL" IN ('Y', 'N')),
   "MEMBER_NO" NUMBER NOT NULL,
   "BOARD_NO" NUMBER NOT NULL,
   "PARENT_COMMENT_NO" NUMBER,
   FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
   FOREIGN KEY ("BOARD_NO") REFERENCES "SHARE" ("BOARD_NO"),
   FOREIGN KEY ("PARENT_COMMENT_NO") REFERENCES "SHARE_COMMENT" ("COMMENT_NO")
);
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_NO" IS '댓글번호(PK)';
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_CONTENT" IS '댓글내용';
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_WRITE_DATE" IS '작성일';
COMMENT ON COLUMN "SHARE_COMMENT"."COMMENT_DEL_FL" IS '댓글삭제 여부(Y/N)';
COMMENT ON COLUMN "SHARE_COMMENT"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "SHARE_COMMENT"."BOARD_NO" IS '나눔 게시글 번호(PK)';
COMMENT ON COLUMN "SHARE_COMMENT"."PARENT_COMMENT_NO" IS '부모댓글번호(FK)';
CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE NOCYCLE;
CREATE TABLE "MESSAGE" (
   "MESSAGE_NO" NUMBER PRIMARY KEY,
   "MESSAGE_TEXT" NVARCHAR2(2000) NOT NULL,
   "MESSAGE_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL,
   "MESSAGE_READ_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("MESSAGE_READ_FL" IN ('Y', 'N')),
   "MESSAGE_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL CHECK ("MESSAGE_DEL_FL" IN ('Y', 'N')),
   "BOARD_NO" NUMBER NOT NULL,
   "SENDER_NO" NUMBER NOT NULL,
   "RECEIVER_NO" NUMBER NOT NULL,
   FOREIGN KEY ("BOARD_NO") REFERENCES "SHARE" ("BOARD_NO"),
   FOREIGN KEY ("SENDER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
   FOREIGN KEY ("RECEIVER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
);
COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '쪽지번호(PK)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_TEXT" IS '쪽지내용';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_WRITE_DATE" IS '쪽지를 작성한 날짜';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_READ_FL" IS '쪽지 읽기 여부(Y/N)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_DEL_FL" IS '쪽지 삭제 여부(Y/N)';
COMMENT ON COLUMN "MESSAGE"."BOARD_NO" IS '나눔 게시글 번호(FK)';
COMMENT ON COLUMN "MESSAGE"."SENDER_NO" IS '회원 고유번호( FK)';
COMMENT ON COLUMN "MESSAGE"."RECEIVER_NO" IS '회원 고유번호(FK)';
CREATE TABLE "JJIM" (
   "MEMBER_NO" NUMBER NOT NULL,
   "BOARD_NO" NUMBER NOT NULL,
   PRIMARY KEY ("MEMBER_NO", "BOARD_NO"),
   FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO"),
   FOREIGN KEY ("BOARD_NO") REFERENCES "SHARE" ("BOARD_NO")
);
COMMENT ON COLUMN "JJIM"."MEMBER_NO" IS '회원 고유번호(PK)';
COMMENT ON COLUMN "JJIM"."BOARD_NO" IS '나눔 게시글 번호(PFK)';
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 회원(MEMBER) 테스트 데이터
INSERT INTO "MEMBER" VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '사용자1', 'user01@example.com', '01012345678', '서울시 강남구 테헤란로 123', SYSDATE, 'N', 1, NULL);
INSERT INTO "MEMBER" VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02', '사용자2', 'user02@example.com', '01023456789', '서울시 서초구 서초대로 456', SYSDATE, 'N', 1, NULL);
INSERT INTO "MEMBER" VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03', '사용자3', 'user03@example.com', '01034567890', '서울시 송파구, 올림픽로 789', SYSDATE, 'N', 1, NULL);
INSERT INTO "MEMBER" VALUES (SEQ_MEMBER_NO.NEXTVAL, 'admin01', 'admin01', '관리자1', 'admin01@example.com', '01045678901', '서울시 중구 세종대로 100', SYSDATE, 'N', 0, NULL);
INSERT INTO "MEMBER" VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user04', 'pass04', '사용자4', 'user04@example.com', '01056789012', '경기도 성남시 분당구 판교로 123', SYSDATE, 'N', 1, NULL);
-- 일반 게시판(BOARD) 테스트 데이터
INSERT INTO "BOARD" VALUES (SEQ_BOARD_NO.NEXTVAL, '자유게시판 첫 게시글입니다', '자유게시판 내용입니다. 반갑습니다!', SYSDATE, NULL, 5, 'N', 2, 1, 'N');
INSERT INTO "BOARD" VALUES (SEQ_BOARD_NO.NEXTVAL, '공지사항: 사이트 이용안내', '이 사이트의 이용방법을 안내합니다.', SYSDATE, NULL, 25, 'N', 3, 4, 'N');
INSERT INTO "BOARD" VALUES (SEQ_BOARD_NO.NEXTVAL, '문의드립니다', '로그인이 되지 않는 문제가 있습니다.', SYSDATE, NULL, 3, 'N', 4, 2, 'N');
INSERT INTO "BOARD" VALUES (SEQ_BOARD_NO.NEXTVAL, '자유게시판 인사글', '안녕하세요! 잘 부탁드립니다.', SYSDATE, NULL, 7, 'N', 2, 3, 'N');
INSERT INTO "BOARD" VALUES (SEQ_BOARD_NO.NEXTVAL, '문의 게시판 글', '비밀번호 변경은 어떻게 하나요?', SYSDATE, NULL, 2, 'N', 4, 5, 'N');
-- 댓글(COMMENT) 테스트 데이터
INSERT INTO "COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '반갑습니다!', SYSDATE, 'N', 1, NULL, 2);
INSERT INTO "COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '공지사항 잘 읽었습니다.', SYSDATE, 'N', 2, NULL, 1);
INSERT INTO "COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '저도 같은 문제가 있었어요', SYSDATE, 'N', 3, NULL, 3);
INSERT INTO "COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '해결방법은 고객센터로 문의하시면 됩니다.', SYSDATE, 'N', 3, 3, 4);
INSERT INTO "COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '감사합니다!', SYSDATE, 'N', 3, 4, 3);
-- 나눔게시판(SHARE) 테스트 데이터
INSERT INTO "SHARE" VALUES (SEQ_BOARD_NO.NEXTVAL, '아이패드 나눔합니다', '거의 새 상품입니다. 필요하신 분에게 나눔합니다.', SYSDATE, NULL, 15, 'N', 1, 1, 'N', 0);
INSERT INTO "SHARE" VALUES (SEQ_BOARD_NO.NEXTVAL, '겨울옷 나눔해요', '입지 않는 겨울옷 나눔합니다. 사이즈 100', SYSDATE, NULL, 8, 'N', 2, 1, 'N', 2);
INSERT INTO "SHARE" VALUES (SEQ_BOARD_NO.NEXTVAL, '파이썬 코딩 도와드립니다', '파이썬 기초부터 심화까지 도와드립니다.', SYSDATE, NULL, 20, 'N', 3, 1, 'N', 13);
INSERT INTO "SHARE" VALUES (SEQ_BOARD_NO.NEXTVAL, '소설책 10권 나눔', '다 읽은 소설책 나눔합니다. 직거래 가능합니다.', SYSDATE, NULL, 12, 'N', 5, 1, 'N', 5);
INSERT INTO "SHARE" VALUES (SEQ_BOARD_NO.NEXTVAL, '디자인 무료로 해드립니다', 'SNS 배너 디자인 무료로 해드립니다.', SYSDATE, NULL, 30, 'N', 2, 1, 'Y', 12);
-- 나눔게시판 댓글(SHARE_COMMENT) 테스트 데이터
INSERT INTO "SHARE_COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '관심 있습니다!', SYSDATE, 'N', 2, 6, NULL);
INSERT INTO "SHARE_COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '쪽지 드렸습니다.', SYSDATE, 'N', 3, 7, NULL);
INSERT INTO "SHARE_COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '파이썬 어느 정도 난이도까지 도와주시나요?', SYSDATE, 'N', 5, 8, NULL);
INSERT INTO "SHARE_COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '기초부터 데이터 분석까지 가능합니다!', SYSDATE, 'N', 3, 8, NULL);
INSERT INTO "SHARE_COMMENT" VALUES (SEQ_COMMENT_NO.NEXTVAL, '와 정말 좋네요! 감사합니다.', SYSDATE, 'N', 5, 8, NULL);
-- 쪽지(MESSAGE) 테스트 데이터
INSERT INTO "MESSAGE" VALUES (SEQ_MESSAGE_NO.NEXTVAL, '아이패드 나눔 가능할까요?', SYSDATE, 'N', 'N', 6, 2, 1);
INSERT INTO "MESSAGE" VALUES (SEQ_MESSAGE_NO.NEXTVAL, '네, 가능합니다. 언제 만날까요?', SYSDATE, 'Y', 'N', 6, 1, 2);
INSERT INTO "MESSAGE" VALUES (SEQ_MESSAGE_NO.NEXTVAL, '파이썬 수업 문의드립니다.', SYSDATE, 'Y', 'N', 8, 5, 3);
INSERT INTO "MESSAGE" VALUES (SEQ_MESSAGE_NO.NEXTVAL, '네, 어떤 부분이 궁금하신가요?', SYSDATE, 'N', 'N', 8, 3, 5);
INSERT INTO "MESSAGE" VALUES (SEQ_MESSAGE_NO.NEXTVAL, '디자인 요청드립니다.', SYSDATE, 'Y', 'N', 10, 1, 2);
-- 찜(JJIM) 테스트 데이터
INSERT INTO "JJIM" VALUES (1, 8);
INSERT INTO "JJIM" VALUES (2, 9);
INSERT INTO "JJIM" VALUES (3, 6);
INSERT INTO "JJIM" VALUES (4, 7);
INSERT INTO "JJIM" VALUES (5, 10);
--test se;ect
-- 회원(MEMBER) 테이블 조회
SELECT * FROM "MEMBER";
-- 게시판(BOARD) 테이블 조회
SELECT * FROM "BOARD";
-- 댓글(COMMENT) 테이블 조회
SELECT * FROM "COMMENT";
-- 나눔게시판(SHARE) 테이블 조회
SELECT * FROM "SHARE";
-- 나눔게시판 댓글(SHARE_COMMENT) 테이블 조회
SELECT * FROM "SHARE_COMMENT";
-- 쪽지(MESSAGE) 테이블 조회
SELECT * FROM "MESSAGE";
-- 찜(JJIM) 테이블 조회
SELECT * FROM "JJIM";
-- 회원별 작성한 게시글 수 조회
SELECT M."MEMBER_NICKNAME", COUNT(B."BOARD_NO") AS 게시글수
FROM "MEMBER" M
LEFT JOIN "BOARD" B ON M."MEMBER_NO" = B."MEMBER_NO"
GROUP BY M."MEMBER_NO", M."MEMBER_NICKNAME"
ORDER BY 게시글수 DESC;
-- 회원별 작성한 댓글 수 조회
SELECT M."MEMBER_NICKNAME", COUNT(C."COMMENT_NO") AS 댓글수
FROM "MEMBER" M
LEFT JOIN "COMMENT" C ON M."MEMBER_NO" = C."MEMBER_NO"
GROUP BY M."MEMBER_NO", M."MEMBER_NICKNAME"
ORDER BY 댓글수 DESC;
-- 게시글과 게시판 종류 함께 조회
SELECT B."BOARD_NO", BT."BOARD_NAME", B."BOARD_TITLE", M."MEMBER_NICKNAME", B."READ_COUNT"
FROM "BOARD" B
JOIN "BOARD_TYPE" BT ON B."BOARD_CODE" = BT."BOARD_CODE"
JOIN "MEMBER" M ON B."MEMBER_NO" = M."MEMBER_NO"
ORDER BY B."BOARD_WRITE_DATE" DESC;
-- 나눔 게시글과 카테고리 정보 함께 조회
SELECT S."BOARD_NO", S."BOARD_TITLE", M."MEMBER_NICKNAME",
      SC."SHARE_BOARD_CATEGORY_NAME", SCD."SHARE_BOARD_CATEGORY_DETAIL_NAME",
      CASE S."SHARE_STATUS" WHEN 'Y' THEN '나눔완료' ELSE '나눔중' END AS 나눔상태,
      S."READ_COUNT"
FROM "SHARE" S
JOIN "MEMBER" M ON S."MEMBER_NO" = M."MEMBER_NO"
JOIN "SHARE_CATEGORY_DETAIL" SCD ON S."SHARE_BOARD_CATEGORY_DETAIL_CODE" = SCD."SHARE_BOARD_CATEGORY_DETAIL_CODE"
JOIN "SHARE_CATEGORY" SC ON SCD."SHARE_BOARD_CATEGORY_CODE" = SC."SHARE_BOARD_CATEGORY_CODE"
ORDER BY S."BOARD_WRITE_DATE" DESC;
-- 게시글별 댓글 수 조회
SELECT B."BOARD_NO", B."BOARD_TITLE", COUNT(C."COMMENT_NO") AS 댓글수
FROM "BOARD" B
LEFT JOIN "COMMENT" C ON B."BOARD_NO" = C."BOARD_NO"
GROUP BY B."BOARD_NO", B."BOARD_TITLE"
ORDER BY 댓글수 DESC;
-- 계층형 댓글 조회 (대댓글 구조 표시)
SELECT
   LPAD(' ', (LEVEL-1)*4) || C."COMMENT_CONTENT" AS 계층형댓글,
   M."MEMBER_NICKNAME",
   C."COMMENT_WRITE_DATE"
FROM "COMMENT" C
JOIN "MEMBER" M ON C."MEMBER_NO" = M."MEMBER_NO"
WHERE C."BOARD_NO" = 3  -- 특정 게시글의 댓글만 조회 (필요에 따라 게시글 번호 변경)
START WITH C."PARENT_COMMENT_NO" IS NULL
CONNECT BY PRIOR C."COMMENT_NO" = C."PARENT_COMMENT_NO"
ORDER SIBLINGS BY C."COMMENT_WRITE_DATE";
-- 나눔 게시글 계층형 댓글 조회
SELECT
   LPAD(' ', (LEVEL-1)*4) || SC."COMMENT_CONTENT" AS 계층형댓글,
   M."MEMBER_NICKNAME",
   SC."COMMENT_WRITE_DATE"
FROM "SHARE_COMMENT" SC
JOIN "MEMBER" M ON SC."MEMBER_NO" = M."MEMBER_NO"
WHERE SC."BOARD_NO" = 8  -- 특정 게시글의 댓글만 조회 (필요에 따라 게시글 번호 변경)
START WITH SC."PARENT_COMMENT_NO" IS NULL
CONNECT BY PRIOR SC."COMMENT_NO" = SC."PARENT_COMMENT_NO"
ORDER SIBLINGS BY SC."COMMENT_WRITE_DATE";
-- 회원별 받은 쪽지함 조회
SELECT
   MSG."MESSAGE_NO",
   발신자."MEMBER_NICKNAME" AS 보낸사람,
   S."BOARD_TITLE" AS 관련게시글,
   MSG."MESSAGE_TEXT",
   MSG."MESSAGE_WRITE_DATE",
   CASE MSG."MESSAGE_READ_FL" WHEN 'Y' THEN '읽음' ELSE '안읽음' END AS 읽음여부
FROM "MESSAGE" MSG
JOIN "MEMBER" 발신자 ON MSG."SENDER_NO" = 발신자."MEMBER_NO"
JOIN "MEMBER" 수신자 ON MSG."RECEIVER_NO" = 수신자."MEMBER_NO"
JOIN "SHARE" S ON MSG."BOARD_NO" = S."BOARD_NO"
WHERE 수신자."MEMBER_NO" = 2  -- 특정 회원의 받은 쪽지만 조회 (필요에 따라 회원 번호 변경)
ORDER BY MSG."MESSAGE_WRITE_DATE" DESC;
-- 회원별 찜한 게시글 조회
SELECT
   M."MEMBER_NICKNAME" AS 회원명,
   S."BOARD_TITLE" AS 찜한게시글,
   SC."SHARE_BOARD_CATEGORY_NAME" AS 카테고리,
   SCD."SHARE_BOARD_CATEGORY_DETAIL_NAME" AS 세부카테고리,
   작성자."MEMBER_NICKNAME" AS 작성자
FROM "JJIM" J
JOIN "MEMBER" M ON J."MEMBER_NO" = M."MEMBER_NO"
JOIN "SHARE" S ON J."BOARD_NO" = S."BOARD_NO"
JOIN "MEMBER" 작성자 ON S."MEMBER_NO" = 작성자."MEMBER_NO"
JOIN "SHARE_CATEGORY_DETAIL" SCD ON S."SHARE_BOARD_CATEGORY_DETAIL_CODE" = SCD."SHARE_BOARD_CATEGORY_DETAIL_CODE"
JOIN "SHARE_CATEGORY" SC ON SCD."SHARE_BOARD_CATEGORY_CODE" = SC."SHARE_BOARD_CATEGORY_CODE"
ORDER BY M."MEMBER_NO";
COMMIT;
-- 여기까지 2025.05.15

